config/routes.rb
Rails.application.routes.draw do
  
  namespace "admin", :module => 'saasaparilla/admin' do
    resources :plans
    resources :subscriptions do
      get 'cancel', :on => :member
      get 'toggle_no_charge', :on => :member
      resources :transactions, :only => [:index]
    end
  end
  
  resource :subscription, :controller => "saasaparilla/subscription" do 
    get 'reactivate', :on => :member
  end
  
  namespace 'subscription', :module => "saasaparilla" do
    resources :payments
    resource :credit_card, :controller => "credit_card"
    resource :plan,  :only => [:edit, :update]
    resource :contact_info, :controller => "contact_info"
    resource :billing_history, :controller => "billing_history"
    resources :invoices
  end
  
  
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_dynamic_attributes
  validates_presence_of :name, :message => "can't be blank"
  validates_presence_of :billing_period, :message => "can't be blank"
  validates_numericality_of :price, :message => "is not a number"
  validates_presence_of :price, :message => "can't be blank"
  
  has_many :subscriptions

  attr_accessible :name, :price, :billing_period
  
  BILLING_PERIODS = ["Monthly", "Annually"]
  
  def respond_to?(method_sym, include_private = false)
      @column_names = []
      unless dynamic_attributes.nil?
        dynamic_attributes.each do |dm|
           @column_names << dm[0].gsub("field_", "")
         end
        if @column_names.include? method_sym.to_s
          return  true
        end
      end

    super
  end
    
  def method_missing(method, *args)
    
    if has_dynamic_attribute?("field_#{method}")
      return self.send("field_#{method}")
    end
    super
   end
       


end

app/controllers/saasaparilla/admin/plans_controller.rb
class Saasaparilla::Admin::PlansController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  include Authorization::InstanceMethods
  
  # GET /plans
  # GET /plans.xml
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.xml
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.xml
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.xml
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to(admin_plans_path, :notice => 'Plan was successfully created.') }
        format.xml  { render :xml => @plan, :status => :created, :location => @plan }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.xml
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to(admin_plans_path, :notice => 'Plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.xml
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to(admin_plans_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/saasaparilla/plans_controller.rb
class Saasaparilla::PlansController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  before_filter :get_subscription, :only => [:edit, :update]
  
  def edit
    @plans = Plan.all(:order => 'price ASC')
  end

  def update
    if params[:subscription][:plan_id] == ""
      @subscription.cancel
      redirect_to(subscription_path, :notice => 'You have been downgraded to the free plan.')
      return
    elsif @subscription.downgrade_plan_to(params[:subscription][:plan_id])
      redirect_to(subscription_path, :notice => 'Plan was successfully changed.')
    else
      render :action => "edit"
    end
  end
  
  private 
  
  def get_subscription
    @subscription = current_billable.subscription
    if @subscription.nil?
      flash[:error] = "You do not have a current subscription"
      redirect_to new_subscription_path
    end
  end
  
  
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/saasaparilla/admin/plans/_form.html.haml
= simple_form_for([:admin, @plan]) do |f| 
	- if @plan.errors.any? 
		#error_explanation
			%h2= "#{pluralize(@plan.errors.count, "error")} prohibited this plan from being saved:"

			%ul
				-@plan.errors.full_messages.each do |msg| 
					%li= msg
	

	= f.input :name
	= f.input :price
	= f.input :billing_period, :collection => Plan::BILLING_PERIODS, :include_blank => false

	%fieldset
		%h4 Plan Attributes
		= f.label "Add new attribute"
		= text_field_tag "attribute_name"
		= link_to "Add attribute", "#", :id => "add_attribute"
		#optional_attributes
			-begin	
				- @plan.dynamic_attributes.each do |da|
					= f.label da[0].gsub("field_", "")
					= text_field_tag "plan[#{da[0]}]",	da[1]
					%br
			- rescue

	.actions
		= f.submit
		= link_to 'Cancel', :back
	
	:javascript
		$(document).ready(function(){
			$('#add_attribute').click(function(event) {
				event.preventDefault();
				if ($('#attribute_name').val() == '') {
					alert("You must give your attribute a name.");
				} else {
					$('#optional_attributes').append("<br><label>" + $('#attribute_name').val() +"</label><input name='plan[field_" + $('#attribute_name').val() +"]' id='field_" + $('#attribute_name').val() +"'>");
				}
			})
		})
		

app/views/saasaparilla/admin/plans/edit.html.erb
<div class="saasaparilla">
<h1>Editing plan</h1>
<%= render 'form' %>
</div>

app/views/saasaparilla/admin/plans/index.html.erb
<div class="saasaparilla">

	<h1>Plans</h1>

	<table>
	  <tr>
	    <th>Name</th>
	    <th>Billing period</th>
	    <th>Subscription</th>
	    <th>Extras</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @plans.each do |plan| %>
	  <tr>
	    <td><%= plan.name %></td>
	    <td><%= plan.billing_period %></td>
	    <td><%= plan.subscription_id %></td>
	    <td><%#= plan.extras %></td>
	    <td><%= link_to 'Show', admin_plan_path(plan) %></td>
	    <td><%= link_to 'Edit', edit_admin_plan_path(plan) %></td>
	    <td><%= link_to 'Destroy', admin_plan_path(plan), :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>

	<p><%= link_to 'New Plan', new_admin_plan_path %></p>

</div>

app/views/saasaparilla/admin/plans/new.html.haml
.saasaparilla
  %h1 New plan
  = render 'form'

app/views/saasaparilla/admin/plans/show.html.haml
.saasaparilla
	%h2 Plan
	%p
		%b Name:
		= @plan.name
	%p
		%b Billing period:
		= @plan.billing_period
	%p
		%b Attributes:
		%br
		- @plan.dynamic_attributes.each do |da|
			= da[0].gsub("field_", "")
			= ": "
			= da[1]
			%br
	%p
		= link_to 'Edit', edit_admin_plan_path(@plan)
		= " | "
		= link_to 'Back', admin_plans_path