config/routes.rb
Rails.application.routes.draw do
  
  namespace "admin", :module => 'saasaparilla/admin' do
    resources :plans
    resources :subscriptions do
      get 'cancel', :on => :member
      get 'toggle_no_charge', :on => :member
      resources :transactions, :only => [:index]
    end
  end
  
  resource :subscription, :controller => "saasaparilla/subscription" do 
    get 'reactivate', :on => :member
  end
  
  namespace 'subscription', :module => "saasaparilla" do
    resources :payments
    resource :credit_card, :controller => "credit_card"
    resource :plan,  :only => [:edit, :update]
    resource :contact_info, :controller => "contact_info"
    resource :billing_history, :controller => "billing_history"
    resources :invoices
  end
  
  
  
end

app/controllers/saasaparilla/accounts_controller.rb
class Saasaparilla::AccountsController < ApplicationController
  unloadable
  #overide with authorization
  def new
    @account = Account.new
    @account.build_contact_info
    @account.build_credit_card
    @subscription = @account.build_subscription

    
  end
  
  
  def create
    @account = Account.new(params[:account])
    
  
      if @account.save
        redirect_to edit_account_path(@account)
        flash[:notice] = "Your account was successfully created."
      else
        render :action => "new"
        flash[:error] = "Your account could not be created due to errors. Please review the form and correct them."
      
      end
  
  end
  
  def edit
    
  end
end

app/controllers/saasaparilla/admin/plans_controller.rb
class Saasaparilla::Admin::PlansController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  include Authorization::InstanceMethods
  
  # GET /plans
  # GET /plans.xml
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.xml
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.xml
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.xml
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to(admin_plans_path, :notice => 'Plan was successfully created.') }
        format.xml  { render :xml => @plan, :status => :created, :location => @plan }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.xml
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to(admin_plans_path, :notice => 'Plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.xml
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to(admin_plans_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/saasaparilla/admin/subscriptions_controller.rb
class Saasaparilla::Admin::SubscriptionsController < ApplicationController
  
  unloadable
  include Authentication::InstanceMethods
  include Authorization::InstanceMethods
  
  # GET /admin/subscriptions
  def index
    @subscriptions = Subscription.paginate(:page => params[:page], :per_page => 20, :order => "created_at DESC")
  end
  
  def show
    @subscription = Subscription.find(params[:id])
  end
  
  def toggle_no_charge
    @subscription = Subscription.find(params[:id])
    @subscription.toggle!(:no_charge)
    redirect_to admin_subscription_path(@subscription)
    if @subscription.no_charge
      flash[:notice] = "Subscription will not be charged."
    else
      flash[:notice] = "Subscription will now be charged."
    end
  end
  
  def cancel
    @subscription = Subscription.find(params[:id])
    @subscription.cancel
    redirect_to admin_subscription_path(@subscription)
    flash[:notice] = "Subscription was canceled."
  end
  
end

app/controllers/saasaparilla/admin/transactions_controller.rb
class Saasaparilla::Admin::TransactionsController < ApplicationController
  
  unloadable
  include Authentication::InstanceMethods
  include Authorization::InstanceMethods
  
  # GET /admin/subscriptions
  def index
    @subscription = Subscription.find(params[:subscription_id])
    @transactions = @subscription.transactions.paginate(:page => params[:page], :per_page => 20, :order => "created_at DESC")
  end
  

end

app/controllers/saasaparilla/application_controller.rb
class Saasaparilla::ApplicationController < ActionController::Base


end

app/controllers/saasaparilla/billing_history_controller.rb
class Saasaparilla::BillingHistoryController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  
  def show
    @billing_activities = current_billable.subscription.billing_activities.order('created_at asc')
    
  end
end

app/controllers/saasaparilla/contact_info_controller.rb
class Saasaparilla::ContactInfoController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  before_filter :get_subscription
  before_filter :get_contact_info
  
  def edit
    
  end
  
  def update
    if @contact_info.update_attributes(params[:contact_info])
      flash[:notice] = "Contact info was successfully updated."
      redirect_to subscription_path
    else
      flash[:error] = "An error has occurred when trying to update your contact info."
      render :action => "edit"
    end
  end
  
  private 
  
  def get_subscription
    @subscription = current_billable.subscription
  end
  
  def get_contact_info
    @contact_info = @subscription.contact_info
  end
  
end

app/controllers/saasaparilla/credit_card_controller.rb
class Saasaparilla::CreditCardController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  ssl_required :edit, :update 
  before_filter :set_subscription
  before_filter :set_credit_cards
  
  
  def edit

  end
  
  def update
    begin 
      if @subscription.credit_card.update_attributes(params[:credit_card])
        flash[:notice] = "Your credit card was successfully updated."
        redirect_to subscription_path
      else
        # @credit_card = @credit_card.reload_with_errors
        render :action => "edit"
        flash[:error] = "Your credit card could not be updated due to errors. Please review the form and correct them."
      end
     rescue Exception => e
          flash[:error] = e.message
          render :action => "edit"
          flash.discard
      end
  end
 
  private 
   
  def set_subscription
    @subscription = current_billable.subscription
  end
  
  def set_credit_cards
    @credit_card = @subscription.credit_card
    @current_card = @credit_card.clone
  end
  
end

app/controllers/saasaparilla/invoices_controller.rb
class Saasaparilla::InvoicesController < ApplicationController
  
  unloadable
  include Authentication::InstanceMethods
  before_filter :get_invoice
  def show
    
  end
  
  
  def get_invoice
    @invoice = Invoice.find(params[:id])
    
    unless @invoice.billing_activity.subscription == current_billable.subscription
      flash[:error] = "Unauthorized to access this invoice"
      redirect_to subscription_path
    end
  end
end

app/controllers/saasaparilla/payments_controller.rb
class Saasaparilla::PaymentsController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  ssl_required :new, :create, :edit, :update, :show 
  before_filter :get_subscription
  before_filter :get_payment, :only => [:edit, :update]
  before_filter :check_pending, :only => [:edit, :update]
  def new
    @payment = @subscription.payments.build
  end
  
  def create
    @payment = @subscription.payments.build(params[:payment])
     if @payment.save
       redirect_to edit_subscription_payment_path(@payment)
     else
       render :action => "new"
     end
  end
  
  def edit
    
  end
  
  def update

    begin
      if @payment.update_attributes(params[:payment])
        flash[:notice] = "Thank you, your payment has been processed."
        redirect_to subscription_payment_path
      else
        flash[:error] = "An error has occured when trying to process your payment."
        render :action => "edit"
      end
    rescue Exception => e
         flash[:error] = e.message
         render :action => "edit"
         flash.discard
    end
  end
  
  def show
    @payment = @subscription.payments.find(params[:id])
  end
  
  
  
  private
  
  def get_subscription
    @subscription = current_billable.subscription
  end
  
  def get_payment

    @payment = @subscription.payments.find(params[:id])

  end
  
  def check_pending
    unless @payment.pending?
      flash[:error] = "Payment has already been paid."
      redirect_to new_subscription_payment_path
    end
    
  end
  
  

  
end

app/controllers/saasaparilla/plans_controller.rb
class Saasaparilla::PlansController < ApplicationController
  unloadable
  include Authentication::InstanceMethods
  before_filter :get_subscription, :only => [:edit, :update]
  
  def edit
    @plans = Plan.all(:order => 'price ASC')
  end

  def update
    if params[:subscription][:plan_id] == ""
      @subscription.cancel
      redirect_to(subscription_path, :notice => 'You have been downgraded to the free plan.')
      return
    elsif @subscription.downgrade_plan_to(params[:subscription][:plan_id])
      redirect_to(subscription_path, :notice => 'Plan was successfully changed.')
    else
      render :action => "edit"
    end
  end
  
  private 
  
  def get_subscription
    @subscription = current_billable.subscription
    if @subscription.nil?
      flash[:error] = "You do not have a current subscription"
      redirect_to new_subscription_path
    end
  end
  
  
  
end

app/controllers/saasaparilla/subscription_controller.rb
class Saasaparilla::SubscriptionController < ApplicationController
  unloadable
  ssl_required :new, :create, :show if Rails.env == "production"
  include Authentication::InstanceMethods
  before_filter :get_subscription, :only => [:show, :destroy, :reactivate]

  before_filter :require_no_subscription, :only => [:new]
  #overide with authorization
  def new
    @subscription = current_billable.build_subscription
    @subscription.build_contact_info
    @subscription.build_credit_card
  end
  
  def create
    @subscription = current_billable.build_subscription(params[:subscription])
    begin
      if @subscription.save
        redirect_to subscription_path
        flash[:notice] = "Your subscription was successfully created."
      else
        render :action => "new"
        flash[:error] = "Your subscription could not be created due to errors. Please review the form and correct them."
      end
    rescue Exception => e
        flash[:error] = e.message
        render :action => "new"
        flash.discard
    end
  end
  
  def show

  end
  
  def reactivate
    if @subscription.reactivate!
      redirect_to subscription_path
      flash[:notice] = "Your subscription was successfully reactivated."
    else
      redirect_to subscription_path
      flash[:error] = "There was a problem reactivating your account."
    end
  end
  
  def destroy
    if @subscription.cancel
      flash[:notice] = "Your subscription has been canceled."
      redirect_to subscription_path
      
    end
  end
  
  private
  def require_no_subscription
    unless current_billable.subscription.nil?
      flash[:error] = "You already have a subscription"
      redirect_to subscription_path
    end
  end
  def get_subscription
    @subscription = current_billable.subscription
    if @subscription.nil?
      flash[:error] = "You do not have a current subscription"
      redirect_to new_subscription_path
    end
  end
  

end

app/helpers/saasaparilla/billing_history_helper.rb
module Saasaparilla::BillingHistoryHelper


end

app/views/saasaparilla/subscription/_contact_info_form.html.haml
= f.input :first_name
= f.input :last_name
= f.input :email
- if @subscription.contact_info.require_billing_address?
	= f.input :address
	= f.input :city
	= f.input :state
	= f.input :zip
	= f.input :country
- if @subscription.contact_info.require_phone_number?
	.input.string.required
		= f.label :phone, :required => true
		= "("
		= f.text_field :phone_area_code, :required => true, :size => 3, :maxlength => 3, :class => "phone_3"
		= ")"
		= f.text_field :phone_prefix, :required => true, :size => 3, :maxlength => 3, :class => "phone_3"
		= " - "
		= f.text_field :phone_suffix, :required => true, :size => 4, :maxlength => 4, :class => "phone_4"
		= f.error :phone_number, :id => 'phone_error'

app/views/saasaparilla/subscription/_credit_card_form.html.haml
= f.input :card_type, :collection => CreditCard::CARD_TYPES, :include_blank => false
- if f.object.new_record?
	= f.input :card_number
- else
	= f.input :card_number, :input_html => {:value => ""}
= f.input :expiry_month, :collection => CreditCard::MONTHS
= f.input :expiry_year, :collection => CreditCard::YEARS,  :error_html => { :id => "subscription_credit_card_attributes_expiry_date_error"}
= f.input :card_verification

app/views/saasaparilla/subscription/new.html.haml
.saasaparilla
	%h1 Create Subscription
	
	= simple_form_for @subscription, :url => subscription_path(:secure => Rails.env == "production") do |f|

		.info
			%h2 Plan
			= f.association :plan, :as => 'radio_buttons', :label => false
	
	
		= f.simple_fields_for :contact_info, @subscription.contact_info do |cif|
			.info
				%h2 Billing Contact Info
				= render :partial => 'contact_info_form', :locals => {:f => cif}
	
		= f.simple_fields_for :credit_card, @subscription.credit_card do |cf|
			.info
				%h2 Billing Payment Info
				= render :partial => 'credit_card_form', :locals => {:f => cf}
	
		
		= f.submit "Create Subscription"
	
	

app/views/saasaparilla/subscription/show.html.haml
.saasaparilla
	%h1 Subscription


	- if @subscription.status == "canceled"
		.info
			%p
				You do not have an active paid subscription. 
				= link_to "Reactivate your previous plan", reactivate_subscription_path, :confirm => "Are you sure you want to reactive your previous plan? Your credit card will be billed immediately."

	- else
		.info
			%h2 Plan

			%p 
				= "You are currently subscribed to the #{@subscription.plan.name} plan."
			%p
				= link_to "Change plan", edit_subscription_plan_path

		.info
			%h2 Billing Contact Info

			%p
				= "#{@subscription.contact_info.first_name} #{@subscription.contact_info.last_name}"
				%br
				= @subscription.contact_info.email
				%br
				- if @subscription.contact_info.require_billing_address?
					= @subscription.contact_info.address
					%br
					= "#{@subscription.contact_info.city}, #{@subscription.contact_info.state} #{@subscription.contact_info.zip}"
					%br
					= @subscription.contact_info.country
					%br
				- if @subscription.contact_info.require_phone_number?
					= "#{@subscription.contact_info.phone_number}"
			%p
				= link_to "Update", edit_subscription_contact_info_path(@subscription.contact_info)
	
		.info
			%h2 Billing Payment Info


			%p
				Card Number
				%br
				= @subscription.credit_card.card_number
			%p
				Expiration
				%br
				=@subscription.credit_card.expiration_date
			%p
				= link_to "Update", edit_subscription_credit_card_path(@subscription.credit_card)
	
		.info
			%h2 Billing History
			%p
				= "Balance: #{number_to_currency(@subscription.balance)}" 
				= link_to "Make a payment", new_subscription_payment_path if @subscription.balance > 0
				%br
				= "Your next billing date is #{@subscription.billing_date.to_s(:month_day_year)}"
				%br
				Your subscription was created on
				= @subscription.created_at.to_s(:month_day_year)
					
			%table.history-table
				= render :partial => 'saasaparilla/billing_history/billing_activity', :collection => @subscription.billing_activities.recent.limit(5)


		.info
			%h2 Actions
			%p
				= link_to "Cancel Subscription", @subscription, :method => "delete", :confirm => "Are you sure you want to cancel your subscription?"